language: c
dist: trusty
sudo: false
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam
install:
  - opam init --yes
  - opam update --yes
  - opam switch --yes $OCAML_VERSION
  - eval `opam config env`
  - opam switch
  - opam install --yes ocamlfind ocamlbuild cppo_ocamlbuild
  - opam upgrade --yes
  - opam list
script:
  - ocamlbuild -use-ocamlfind -plugin-tag "package(cppo_ocamlbuild)" -tag debug unit_tests.byte
  - _build/src/unit_tests.byte
env:
  - OCAML_VERSION=4.02.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.05.0+flambda
cache:
  directories:
  - $HOME/.opam
